# Jekyll Settings

title: Test
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "https://mattdemers.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
permalink: /:title/

# Plugins

plugins:
  - jekyll-feed
  - jekyll-include-cache


# Minimal Mistakes

minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-CA"

# Post Defaults

#defaults:
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
